Undefined FormData cause exception.
Issue:

```

node_modules/mailgun.js/interfaces/IFormData.d.ts:6:20 - error TS2304: Cannot find name 'HTMLFormElement'.

6     new (options?: HTMLFormElement | IFormDataOptions): NodeFormData | FormData;
                     ~~~~~~~~~~~~~~~

node_modules/mailgun.js/interfaces/IFormData.d.ts:6:72 - error TS2304: Cannot find name 'FormData'.

6     new (options?: HTMLFormElement | IFormDataOptions): NodeFormData | FormData;
                                                                         ~~~~~~~~

node_modules/mailgun.js/request.d.ts:20:127 - error TS2304: Cannot find name 'FormData'.

20     command(method: string, url: string, data?: Record<string, unknown> | Record<string, unknown>[] | string | NodeFormData | FormData, options?: Record<string, unknown>, addDefaultHeaders?: boolean): Promise<APIResponse>;
                                                                                                                                 ~~~~~~~~


Found 3 errors in 2 files.

Errors  Files
     2  node_modules/mailgun.js/interfaces/IFormData.d.ts:6
     1  node_modules/mailgun.js/request.d.ts:20


```